version: "3.2"
services:
  express-server:
    image: node:10
    working_dir: /usr/app
    volumes:
      - ./src/express-server:/usr/app
    command: bash -c "npm install && npm start"
    ports:
      - "3001:3000"
    environment:
      - TS_NODE_CACHE_DIRECTORY=/tmp
    tty: true

  e2e:
    image: node:8
    working_dir: /usr/app
    volumes:
      - ./src/e2e:/usr/app
    command: bash -c "npm install && npm test"
    links:
      - express-server
    environment:
      - TS_NODE_CACHE_DIRECTORY=/tmp
      - EXPRESS_SERVER_HOST=express-server
    tty: true
